[start]
cmd = "node .output/server/index.mjs"

[variables]
NODE_ENV = "production"
NITRO_PRESET = "node-server"

[phases.build]
dependsOn = ["setup"]
cmds = [
  "npm ci",
  "npm run build"
]

[phases.setup]
nixPkgs = ["nodejs-20_x"]
nixLibs = ["nodejs-20_x"]
