[variables]
NODE_ENV = "production"
NITRO_PRESET = "node-server"

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci --prefer-offline --no-audit --no-fund"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
cmd = "npm run start"